### PR TITLE
Restructured the project, updated dependencies and fixed the entry point for NPM

### PR DESCRIPTION
**Pull request by Teoxoy**

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Thank you! I see that project is still doesnt use `checkpack`. I'll use it same way we do it in `pixi-spine` and `pixi-tilemap` :)

**Comment by Teoxoy** [comment]
Thanks for the fast response. Using checkpack would be best. I mainly restructured the project because I had issues loading it with webpack. I can implement checkpack and commit here again, would you like that?

**Comment by ivanpopelyshev** [comment]
No, I'll do it today :)

**Comment by ivanpopelyshev** [comment]
Done, added checkpack, all moved to `PIXI.picture`

**Pull request closed without merging**
